apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nodejs-zsuhxhkw 
  janus-idp.io/tekton: nodejs-zsuhxhkw
  backstage.io/kubernetes-id: nodejs-zsuhxhkw
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nodejs-zsuhxhkw
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml